export enum RolePair {
    PresidentBoomer = 1,
    DoctorEngineer = 2,
    TuesdayKnightDrBoom = 3,
    Enforcer = 4,
    Mayor = 5,
    Coyboy = 6,
    Papanoid = 7,
    Spy = 8,
    Usurper = 9,
    Security = 10,
    ErisCupid = 11,
    RivalIntern = 12,
    ButlerMaid = 13,
    WifeMistress = 14,
    SurvivorVictim = 15,
    RomeoJuliet = 16,
    AhabMoby = 17,
    BombBotQueen = 18,
    DecoyTargetSniper = 19,
    Gambler = 20
}